version: '3'
services:
  database:
    image: postgres:11.5
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
volumes:
  pgdata:
